/* Location-first discovery content. Source observations: September 15, 2026. */
(() => {
  const esc = s => String(s || '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const asset = n => '../assets/'+n+'.jpg';
  const section = name => [...document.querySelectorAll('[data-loc]')].find(x=>x.dataset.loc===name);
  const photo = (name,label) => `<figure><img loading="lazy" src="${esc(name.startsWith('http')?name:asset(name))}" alt="${esc(label)}"><figcaption>${esc(label)}</figcaption></figure>`;
  function gallery(name,photos){const s=section(name);s.querySelector('.photos').outerHTML='<div class="photos">'+photos.map(x=>photo(...x)).join('')+'</div>';}
  const item=(name,kind,description,image,url,caption='')=>({name,kind,description,image,url,caption});
  function card(x,loc){let img=x.image?`<figure><img loading="lazy" src="${esc(x.image.startsWith('http')?x.image:asset(x.image))}" alt="${esc(x.caption||x.name)}">${x.caption?'<figcaption>'+esc(x.caption)+'</figcaption>':''}</figure>`:'';return `<article class="discovery-card">${img}<div class="card-body"><div class="card-kind">${esc(x.kind)}</div><h4>${esc(x.name)}</h4><p>${esc(x.description)}</p>${x.deal?'<p class="deal">'+esc(x.deal)+'</p>':''}<div class="card-links"><a target="_blank" rel="noopener" href="${esc(x.url)}">Details ↗</a><a target="_blank" rel="noopener" href="${esc(x.maps||'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(x.name+' '+loc))}">Google Maps ↗</a></div><button class="pick">Add to trip</button></div></article>`;}
  function pane(loc,tab,groups){let s=section(loc),p=s.querySelector(`[data-tab="${tab}"]`);if(!p){p=document.createElement('div');p.className='pane';p.dataset.tab=tab;s.querySelector('.tabs').after(p);}p.innerHTML='<p class="browse-hint">Browse the options. On a phone, swipe across each row.</p>'+groups.map(([title,items])=>`<h3 class="card-group-title">${esc(title)}</h3><div class="card-row">${items.map(x=>card(x,loc)).join('')}</div>`).join('');}
  gallery('Breckenridge/Frisco area',[['frisco','Frisco Main Street'],['breck','Breckenridge Main Street']]);
  gallery('Leadville / Twin Lakes',[['discovery-leadville-saloon','Silver Dollar Saloon · Harrison Avenue'],['leadville','Leadville and the surrounding mountains']]);
  gallery('Crested Butte',[['discovery-cb-elk','Elk Avenue · Crested Butte'],['discovery-gothic','Gothic Mountain'],['discovery-cb-sunny','Autumn colors near Crested Butte']]);
  gallery('Telluride',[['telluride','Colorado Avenue · Telluride'],['discovery-telluride-gondola','Gondola above Telluride'],['discovery-bridal-veil','Bridal Veil Falls and powerhouse']]);
  gallery('Corona Arch',[['arches','Arches National Park'],['moab','Corona Arch'],['discovery-slickrock','Mountain biking on Slickrock']]);
  section('Crested Butte').querySelector('.lede').textContent='Elk Avenue, mountain views and a beer after a short walk. Add Gothic Valley, a fall-color drive or a ride when there’s energy for more.';
  section('Telluride').querySelector('.lede').textContent='A town tucked into a steep box canyon. Ride the gondola, walk to waterfalls, or make a bigger day of the via ferrata.';
  section('Leadville / Twin Lakes').querySelector('.lede').textContent='Harrison Avenue and the Silver Dollar Saloon make a good passing stop. Continue west afterward; Twin Lakes camping is an option if it’s getting late.';
  section('Corona Arch').querySelector('h2').textContent='Moab';section('Corona Arch').id='moab';section('Telluride').id='telluride';section('Crested Butte').id='crested-butte';
  section('Corona Arch').querySelector('.lede').textContent='Three nights to mix sandstone scenery, river time, riding and town. Pick one main outing each day and leave the rest open.';
  const tell='https://www.telluride.com/activity/';
  pane('Telluride','Do',[
    ['Town and big views',[
      item('Telluride gondola','Scenic ride · low effort','Ride between town and Mountain Village for the canyon panorama. Check operating hours.','discovery-telluride-gondola',tell+'gondola/'),
      item('Bridal Veil Falls trail','Waterfall hike','Walk to the base of the falls. The powerhouse sits above; the onward road is a separate extension.','discovery-bridal-veil',tell+'bridal-veil-falls-trail/'),
      item('Jud Wiebe loop','Short, steep hike','A climb straight from town with views across the valley. Short distance still means a proper uphill effort.','https://www.telluride.com/site/assets/files/9368/1464386660ec116cac.jpg',tell+'jud-wiebe-trail/')]],
    ['A bigger day',[
      item('Telluride via ferrata','Exposed climbing traverse','An optional adventure on the canyon wall. Proper via-ferrata equipment and competence are essential; book a guide if needed.','https://www.telluride.com/site/assets/files/37177/viaferrata-12-large.webp',tell+'telluride-via-ferrata/')]]]);
  pane('Crested Butte','Do',[
    ['Short walks and scenic drives',[
      item('Elk Avenue town wander','Coffee · shops · mountain town','Start with the colorful main street, then choose lunch or a pub.','discovery-cb-elk','https://gunnisoncrestedbutte.com/'),
      item('Lower Loop / Woods Walk','Easy walk or mellow ride','Meadows, river scenery and mountain views close to town. Turn around whenever you like.','https://gunnisoncrestedbutte.com/wp-content/uploads/lower-loop-trail-crested-butte-1024x768.jpg','https://gunnisoncrestedbutte.com/blog/best-trailheads-near-gunnison-and-crested-butte/','Lower Loop trail'),
      item('Gothic Valley drive','Mountain scenery','A scenic outing toward Gothic beneath its namesake mountain. Check road conditions before extending farther.','discovery-gothic','https://gunnisoncrestedbutte.com/blog/things-to-do-in-gothic/','Gothic Mountain'),
      item('Kebler Pass fall-color drive','Seasonal road','A scenic connection or an out-and-back, with stops among the autumn aspens.','cb-fall','https://gunnisoncrestedbutte.com/','Fall landscape near Crested Butte')]],
    ['If riding sounds good',[
      item('Dyke Trail / Lake Irwin loop','Intermediate–advanced MTB','A bigger ride in the Kebler Pass area with climbing and technical sections. Check the current trail report.','', 'https://gunnisoncrestedbutte.com/blog/crested-butte-mountain-bike-trails/'),
      item('Trail 401','High-country MTB day','The classic mountain-scenery ride. Choose it for a settled-weather day; check access and trail conditions first.','https://gunnisoncrestedbutte.com/wp-content/uploads/trail-401-crested-butte-300x225.jpg', 'https://gunnisoncrestedbutte.com/blog/crested-butte-mountain-bike-trails/')]]]);
  pane('Aspen','Do',[
    ['Views without committing the whole day',[
      item('Maroon Lake Scenic Loop','Easy walk · Bells access reservation','The classic lake-and-peaks view. Arrange parking or shuttle access separately from camping.','mountains','https://www.aspensnowmass.com/visit/activities/summer/maroon-bells','Maroon Bells over Maroon Lake'),
      item('Aspen downtown stroll','Town walk','Historic streets, coffee and a look around before heading back to camp.','aspen-town','https://aspenchamber.org/','Downtown Aspen')]],
    ['Longer outing',[
      item('Crater Lake trail','Moderate hike','Continue beyond Maroon Lake into the basin. Check the current trail report and leave time for the return shuttle.','mountains','https://www.aspensnowmass.com/visit/activities/summer/maroon-bells','The Maroon Bells basin; photo taken at Maroon Lake')]]]);
  const bike='https://www.discovermoab.com/attractions/mountainbiking/';
  pane('Corona Arch','Do',[
    ['Scenery, short walks and something unexpected',[
      item('Arches scenic drive + short walks','Half-day option','Choose the Windows area, Balanced Rock and roadside viewpoints; no need to turn every stop into a hike.','arches','https://www.nps.gov/arch/planyourvisit/index.htm','Arches National Park'),
      item('Corona Arch trail','Hike · railway crossing · short cable section','The arch walk off Potash Road: open sandstone, a railway crossing and a big freestanding arch.','moab','https://www.blm.gov/visit/corona-arch-trail'),
      item('Dead Horse Point','Viewpoint · sunset option','A huge canyon-and-river panorama with short rim walks. An extra outing northwest of Moab.','discovery-dead-horse','https://stateparks.utah.gov/parks/dead-horse/'),
      item('Mill Canyon dinosaur sites','Short interpretive walks','Real dinosaur tracks and exposed fossil bones north of town. A different kind of roadside stop.','https://live.staticflickr.com/1501/26151850696_8bbe27bbd0_n.jpg','https://www.blm.gov/visit/mill-canyon-dinosaur-trailhead-interpretive-site','Mill Canyon Dinosaur Tracksite')]],
    ['Mountain biking · choose the effort',[
      item('Slickrock Trail','Technical MTB · Sand Flats','Try the practice loop before committing to the main route. Grippy sandstone, repeated steep climbs and big views.','discovery-slickrock','https://www.discovermoab.com/attractions/mountainbiking/mountain-biking-trail-maps/'),
      item('Raptor Route shuttle','Intermediate–difficult MTB','A downhill-oriented trail chain. Arrange a shuttle or choose a shorter section; it is still real mountain biking.','https://www.hazardcountyshuttle.com/static/8baf838ac295335879c44e3cfdf38993/de8d1/raptor-route-hero.jpg','https://www.hazardcountyshuttle.com/mtb-shuttles/raptor-route/'),
      item('Moab Brands / Bar M','Easier MTB options','A flexible trail network. Start with Rusty Spur or a shorter Bar M option and add mileage if it feels good.','',bike),
      item('Navajo Rocks','Intermediate MTB','Rolling sandstone and desert singletrack. Choose a section rather than committing to every loop.','',bike),
      item('Captain Ahab','Expert MTB · exposed technical sections','A demanding ride with ledges, climbing and exposure. Keep it for a day when both want technical riding.','', 'https://www.discovermoab.com/trail/captain-ahab/682dec7b7e17296df3b99600/'),
      item('Whole Enchilada / Porcupine Rim','Big shuttle day · advanced riding','The famous long descent, with demanding terrain and pedaling. The highest available drop-off depends on conditions.','', 'https://wholeenchiladashuttles.com/shuttle-info-and-rates/')]],
    ['Let someone else handle the logistics',[
      item('Dan Mick’s guided Jeep tour','Paid passenger trip · Hell’s Revenge','Choose a shorter or longer guided Jeep outing. Agree on the level of obstacles when booking; extra obstacles can cost more.','', 'https://www.danmick.com/'),
      item('Hell’s Revenge guided 4×4 tour','Paid off-road outing','Ride as passengers with a guide over the sandstone fins. Sunset tours are an option; this operator uses Hummers.','https://irp.cdn-website.com/8237dfbc/dms3rep/multi/opt/moab-hummer-tours-rear-wide-open-hero1-1920w.jpg','https://www.moabadventurecenter.com/tours/hummer-tour-sunset'),
      item('Colorado River half-day float','Paid river trip','A change of pace among river cliffs, with some splashy sections. Confirm late-September departures and water conditions.','https://irp.cdn-website.com/8237dfbc/dms3rep/multi/opt/moab-sampler-rafting-floating-with-la-sal-mountains-in-background-1920w.JPG','https://www.moabadventurecenter.com/tours/colorado-river-rafting-morning')]]]);
  const stay=section('Corona Arch').querySelector('[data-tab="Stay"]');
  stay.insertAdjacentHTML('afterbegin','<div class="item"><h4>Sand Flats Recreation Area campgrounds</h4><p>The camping area beside the Slickrock riding zone. Individual sites are first-come, first-served; bring drinking water. Vault toilets, no campground showers. Arrive earlier if this is the preferred base.</p><a href="https://grandcountyutah.net/289/Camping" target="_blank" rel="noopener">Campground details ↗</a> · <a href="https://www.google.com/maps/search/?api=1&query=Sand+Flats+Recreation+Area+campground+Moab" target="_blank" rel="noopener">Google Maps ↗</a></div>');
  const big=section("Big B's Orchards");big.querySelector('[data-tab="Do"]')?.remove();
  const bigImg=big.querySelector('.photos img').src;
  pane("Big B's Orchards",'Pub',[['If passing near Paonia',[item('Big B’s cider garden','Cider · outdoor tables','A cider and a relaxed break after lunch. Simply a pleasant stop if the route goes this way.',bigImg,'https://www.bigbs.com/')]]]);
  const fork=document.querySelector('#desert-map').closest('.branch');
  fork.querySelector('.cols').classList.add('fork-cards');
  fork.querySelector('.cols').innerHTML=[
    {name:'North · scenic roads and varied stops',route:'Torrey / Capitol Reef → Escalante → Bryce',pics:[['reef','Capitol Reef cliffs'],['escalante','Escalante canyon country'],['bryce','Bryce hoodoos']],good:['UT-24 cliffs and Highway 12’s changing landscapes','Short rim walks at Bryce; longer hikes if wanted','Capitol Reef: Hickman Bridge or a scenic-drive stop','Escalante adds canyon walks and small-town food stops'],trade:['More winding-road time; two days means choosing highlights','High-elevation nights can be cold','Slot-canyon plans depend on rain, road conditions and access'],fit:'Best for a scenic drive with several different kinds of stops.'},
    {name:'South · iconic desert landmarks',route:'Monument Valley → Page / Antelope Canyon',pics:[['monument','Monument Valley'],['discovery-antelope','Antelope Canyon'],['grand','Grand Canyon · separate detour']],good:['Monument Valley’s sandstone buttes and Western-film scenery','A Navajo-guided Antelope Canyon tour','Horseshoe Bend and Lake Powell near Page','Option to trade other stops for a Grand Canyon detour'],trade:['Antelope needs a timed guided-tour booking','Longer exposed desert stretches and limited shade','Grand Canyon adds substantial driving; it is not on the direct road to Zion'],fit:'Best if Monument Valley and Antelope are the must-see sights.'}
  ].map(x=>`<div><h4>${x.name}</h4><p>${x.route}</p><p class="fork-date">Tentative: September 27–28</p><div class="photos">${x.pics.map(p=>photo(...p)).join('')}</div><p>${x.fit}</p><div class="fork-facts"><div><h5>What you get</h5><ul>${x.good.map(t=>'<li>'+t+'</li>').join('')}</ul></div><div class="tradeoff"><h5>What you give up / plan around</h5><ul>${x.trade.map(t=>'<li>'+t+'</li>').join('')}</ul></div></div></div>`).join('');
  const vegas=document.createElement('section');vegas.className='loc';vegas.dataset.loc='Las Vegas surroundings';vegas.innerHTML='<div class="region">Optional final-day detours</div><h2>On the way to Las Vegas?</h2><p class="visit-date">October 2 · optional; no extra Vegas nights</p><p class="lede">Valley of Fire fits the approach from Zion. Hoover Dam and Red Rock Canyon are separate outings from Vegas. Skip these if there has been enough red rock already.</p><div class="tabs"></div>';fork.after(vegas);
  pane('Las Vegas surroundings','Do',[['Three distinct options',[
    item('Valley of Fire State Park','Optional detour off the I-15 approach','Red sandstone and short viewpoints northeast of Vegas. About 35 extra road miles on the plotted route. An October 2 option; check trail and entrance alerts.','discovery-valley-fire','https://parks.nv.gov/parks/valley-of-fire'),
    item('Hoover Dam','Engineering landmark · separate detour','Southeast of Vegas, beyond the direct Zion route. The plotted drive is about 34 miles each way; allow a separate outing.','discovery-hoover','https://www.usbr.gov/lc/hooverdam/service/directions.html'),
    item('Red Rock Canyon','Optional scenic drive · west of Vegas','The conservation area with a 13-mile scenic loop and climbing cliffs. About 19 road miles each way from central Vegas; check October timed-entry requirements.','https://cdn.recreation.gov/public/2020/02/14/20/36/1826_7af5dc7d-c59c-4f3e-a7bf-43b28c55ee6f_1440.webp','https://www.blm.gov/visit/red-rock-canyon-national-conservation-area')]]]);
  // Food research is loaded before this script; keep venue photos attached to the actual venue.
  const mapLoc={Frisco:'Breckenridge/Frisco area',Breckenridge:'Breckenridge/Frisco area',Dillon:'Breckenridge/Frisco area',Gunnison:'Crested Butte',Leadville:'Leadville / Twin Lakes',Moab:'Corona Arch','Moab / UT-128':'Corona Arch','Telluride / Mountain Village':'Telluride'};
  const grouped={};
  (window.roadtripFood||[]).forEach(v=>{const loc=mapLoc[v.location]||v.location;if(!section(loc))return;const tab=v.kind==='pub'?'Pub':'Eat';const key=loc+'|'+tab;(grouped[key]||=[]).push({...item(v.name,tab==='Pub'?'Brewery / tavern':'Casual food',(v.location==='Gunnison'?'If passing through Gunnison: ':'')+v.highlight,v.imageUrl,v.url),maps:v.googleMapsUrl,deal:v.happyHour,caption:v.imageCaption});});
  Object.entries(grouped).forEach(([key,items])=>{let[loc,tab]=key.split('|');pane(loc,tab,[[tab==='Pub'?'Beer, taprooms and taverns':'A few places worth choosing between',items]]);});
  const aspenBeer=(window.roadtripFood||[]).find(v=>v.location==='Aspen');if(aspenBeer)pane('Aspen','Eat',[['An easy town meal',[item('Aspen Brewing Company pizza','Pizza · in town','A casual pizza-and-beer option on South Galena Street. Check the current menu before choosing.',aspenBeer.imageUrl,aspenBeer.url)]]]);
  document.querySelectorAll('section.loc,details.optional-stop').forEach(s=>{const tabs=s.querySelector('.tabs');['Stay','Do','Eat','Pub','Events'].forEach(t=>{const p=s.querySelector(`[data-tab="${t}"]`);if(p)tabs.parentElement.append(p);});});
  document.querySelectorAll('.discovery-card img').forEach(img=>img.addEventListener('error',()=>img.closest('figure').remove()));
  document.querySelector('details.design')?.remove();
})();
