/* September 2026: simplify the field guide around its location chapters. */
(()=>{
const $=s=>document.querySelector(s);
const overview=$('.mapbox');overview.querySelector('p').outerHTML='<ol class="route-spine"><li>Denver airport</li><li>Breckenridge / Frisco</li><li>Aspen OR Crested Butte</li><li>Telluride</li><li>Moab</li><li class="utah-choice"><div><strong>Utah: choose one route</strong><div>Monument Valley → Page</div><b class="route-or">OR</b><div>Capitol Reef → Escalante → Bryce</div></div></li><li>Zion · Bryce optional</li><li>Las Vegas</li></ol>';
$('.route-note').remove();
$('.weekend-calendar')?.remove();$('.weekend-note')?.remove();
$('#tentative-dates h3').textContent='Nights along the way';
$('#tentative-dates > p').textContent='Working dates for lodging. Friday–Sunday nights are highlighted; confirm the route before booking.';
function weekends(){document.querySelectorAll('.date-row').forEach((r,i)=>{r.classList.toggle('busy-night',[0,1,3,4,7].includes(i));const b=r.querySelector('b');if(b){b.textContent=b.textContent.replace('Sep 19 ·','Sat Sep 19 ·').replace('Sep 20–21 ·','Sun–Mon Sep 20–21 ·').replace('Sep 24–26 ·','Thu–Sat Sep 24–26 ·').replace('Sep 27–28 ·','Sun–Mon Sep 27–28 ·');}});}
weekends();document.querySelectorAll('[data-colorado],[data-desert]').forEach(b=>b.addEventListener('click',weekends));
const vegas=$('#vegas-anchor');vegas.className='loc';vegas.dataset.loc='Las Vegas';vegas.id='las-vegas';vegas.querySelector('h3').outerHTML='<div class="region">Final stop · October 2–3</div><h2>Las Vegas</h2><p class="visit-date">Friday October 2 night · Saturday October 3 departure</p><h3>Things to do</h3>';
const desertMap=$('#desert-map');const fork=desertMap.closest('.branch');fork.after(vegas);const detours=$('[data-loc="Las Vegas surroundings"]');if(detours){const d=document.createElement('details');d.className='vegas-detours';d.innerHTML='<summary>Optional nearby detours</summary>';const row=detours.querySelector('.card-row');if(row)d.append(row);vegas.append(d);detours.remove();}
vegas.querySelector('.card-row').insertAdjacentHTML('beforeend','<article class="discovery-card"><div class="card-body"><div class="card-kind">Beer hall · optional</div><h4>Hofbräuhaus Oktoberfest</h4><p>Oktoberfest runs September 11–October 31. The October 2 celebrity event is 6–11 p.m., overlapping hockey. Choose an October 1 visit only if arriving early; October 3’s evening event does not fit the flight.</p><div class="card-links"><a href="https://www.hofbrauhauslasvegas.com/events/month/2026-10/" target="_blank" rel="noopener">Dates & reservations ↗</a><a href="https://www.google.com/maps/search/?api=1&query=Hofbrauhaus+Las+Vegas" target="_blank" rel="noopener">Google Maps ↗</a></div></div></article>');
const coloradoSection=$('#colorado-fork');coloradoSection.querySelector('h3').textContent='Colorado route choice';coloradoSection.querySelector('p').textContent='Aspen or Crested Butte fits two nights. Visiting both splits the nights and adds the drive around the Elk Mountains.';
const cols=coloradoSection.querySelector('.cols');if(cols)cols.innerHTML='<div><h4>Aspen</h4><p>Maroon Bells and the resort town. Plan access to the Bells.</p></div><div><h4>Crested Butte</h4><p>Elk Avenue, Gothic Valley and camping. The more relaxed town option.</p></div><div><h4>Both</h4><p>One night each; connect around the mountains via CO-133 and Kebler Pass if open.</p></div>';
coloradoSection.querySelector('[data-colorado="compare"]')?.remove();$('#colorado-status').hidden=true;
fork.querySelector('h3').textContent='Moab to Zion: two route options';fork.querySelector('p').textContent='The southern route is the current plan. The northern route takes different roads; combining both means extra driving and fewer nights at each stop.';
fork.querySelector('.cols').innerHTML='<div><h4>South · current plan</h4><p>Monument Valley → Page → Zion</p><p>Western scenery and Antelope Canyon. Reserve the guided tour; one Page night usually fits.</p></div><div><h4>North · alternative</h4><p>Capitol Reef → Escalante → Bryce → Zion</p><p>Highway 12, slot canyons and hoodoos. More winding roads; replaces Monument Valley and Page.</p></div>';
fork.querySelector('[data-desert="compare"]')?.remove();
const bryce=$('#bryce-option');if(bryce){bryce.querySelector('h3').textContent='Bryce can still fit';bryce.querySelector('details')?.remove();bryce.querySelector('.route-buttons')?.remove();const ps=bryce.querySelectorAll('p');ps.forEach((p,i)=>{if(i>1)p.remove();});}
desertMap.src='terrain.html?scope=desert&choice=south&bryce=1';$('#overview-map').src='terrain.html?scope=overview&desert=south&bryce=1';
window.bryceOption=true;
function syncSpine(){const legs=document.querySelectorAll('.route-spine > li');legs[2].textContent=co==='aspen'?'Aspen':co==='cb'?'Crested Butte':co==='both'?'Aspen + Crested Butte':'Aspen OR Crested Butte';}
document.querySelectorAll('[data-colorado],[data-desert]').forEach(b=>b.addEventListener('click',syncSpine));

$('.design')?.remove();document.querySelectorAll('.browse-hint').forEach(x=>x.remove());

function setPhoto(name,url,label,source){const c=[...document.querySelectorAll('.discovery-card')].find(c=>c.querySelector('h4')?.textContent===name);if(!c)return;let f=c.querySelector('figure');if(!f){f=document.createElement('figure');c.prepend(f);}f.innerHTML=`<img loading="lazy" src="${url}" alt="${label}"><figcaption><a href="${source}" target="_blank" rel="noopener">${label}</a></figcaption>`;}
setPhoto('Paradise Divide camping','https://live.staticflickr.com/65535/53907337527_4f6b0b16b6_b.jpg','Paradise Divide · Reid Northrup','https://www.flickr.com/photos/reid1956/53907337527');
setPhoto('Gothic Valley drive','https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/media/images/GothicMtn.jpg','Gothic in fall · Corey Lawrence / USGS','https://www.usgs.gov/media/images/gothic-mountain-fall-town-gothic-colorado');
const moabEvents=$('[data-loc="Corona Arch"] [data-tab="Events"]');if(moabEvents){const p=document.createElement('p');p.className='event-note';p.innerHTML='No date-confirmed Moab Oktoberfest found in the checked calendars. The September 26 Red Rock Arts street festival has a beer garden. <a href="https://www.discovermoab.com/events/" target="_blank" rel="noopener">Moab calendar ↗</a>';moabEvents.prepend(p);}


// Location-specific additions, checked September 15, 2026.
const card=(title,kind,body,url,map)=>`<article class="discovery-card"><div class="card-body"><div class="card-kind">${kind}</div><h4>${title}</h4><p>${body}</p><div class="card-links"><a href="${url}" target="_blank" rel="noopener">Details & dates ↗</a><a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(map||title)}" target="_blank" rel="noopener">Google Maps ↗</a></div></div></article>`;
const showCard=[...vegas.querySelectorAll('.discovery-card')].find(c=>c.querySelector('h4')?.textContent==='Cirque du Soleil');
showCard.outerHTML=card('“O” · Cirque du Soleil','Thursday October 1 · Bellagio','Diving, acrobatics and a stage that becomes a pool. Live calendar: 6:30 p.m. from $135 or 9 p.m. from $145, including service fee, before tax. Prices checked September 15; select the performance to confirm. Friday shows overlap the hockey evening.','https://bellagio.mgmresorts.com/redirect/show-name/o-by-cirque-du-soleil','O Theatre Bellagio Las Vegas');
const extras=document.createElement('details');extras.className='vegas-detours';extras.innerHTML='<summary>Arriving early? More shows, swimming & beer</summary><p>Use October 1, or October 2 daytime before hockey. Choose one or two.</p><div class="card-row">'+
card('Mad Apple · Cirque du Soleil','Comedy, live music & acrobatics','A livelier, comedy-led alternative at New York–New York. Published 2026 Thursday schedule: 7 or 9:30 p.m. Exact October 1 inventory still needs checking. KÀ and Mystère are normally dark on Thursdays.','https://www.cirquedusoleil.com/mad-apple/buy-tickets','Mad Apple New York New York Las Vegas')+
card('Stadium Swim','Pool day · Circa, downtown','Six pools and a huge sports screen. October 1 has a listed pro-football pool event; October 2 has regular weekday admission. A pool-and-sports afternoon rather than a confirmed headline-DJ party. Check day-entry price.','https://www.circalasvegas.com/event/EVE53555600020261001/pro-football-at-stadium-swim/','Stadium Swim Circa Las Vegas')+
card('Able Baker Brewing','Arts District · brewery & kitchen','Over 30 taps, a covered patio and food from Arts District Kitchen. A straightforward lunch-and-beer stop on Main Street. The official site links its current downtown happy-hour menu.','https://www.ablebakerbrewing.com/downtown-brewery','Able Baker Brewing 1510 South Main Las Vegas')+
card('The Range 702','Supervised indoor shooting','A compact beginner session is enough: the One and Done package is advertised from $79.95 per person. Instructor and safety equipment are part of the experience. Bring government ID; visit before any beers. Confirm package price and eligibility with the venue.','https://www.therange702.com/shooting-experiences/','The Range 702 Las Vegas')+
card('Boulder Beach · Lake Mead','Natural lake swim · optional detour','A rocky lakeshore swimming option near Boulder City, useful alongside Hoover Dam. Bring water shoes; use the designated swim beach and check current access and water advisories. No lifeguards. Allow the extra drive outside Vegas.','https://www.nps.gov/lake/planyourvisit/swimming-beaches.htm','Boulder Beach Lake Mead')+
card('UNLV vs California','Saturday October 3 · 12:30 p.m. Pacific','College football at Allegiant Stadium. Possible departure-day outing, but tight with the 7:20 p.m. international flight: plan to leave early and reach the airport around 4:20 p.m., allowing separately for bags and transport. Moab’s homecoming game is the easier fit.','https://www.allegiantstadium.com/events/detail/unlv-rebels-vs-cal-2026','Allegiant Stadium Las Vegas')+'</div>';vegas.append(extras);
const page=document.createElement('section');page.className='loc';page.id='page-camping';page.innerHTML='<div class="region">Southern route · Page / Lake Powell</div><h2>A night by the lake</h2><p class="visit-date">Tentative: September 27 · Antelope Canyon September 28</p><div class="card-row">'+card('Lone Rock Beach primitive camping','Stay · lake views & beach access','The strongest fit for a flexible lakeside night: unnumbered beach camping, no reservations. $14 per vehicle/night plus park admission. This is paid primitive camping, not free dispersed land. Soft sand gets deeper toward the water; pick a sensible access line. Bring drinking water. Shoreline distance and facilities vary with lake level and season. Photo: June 2023, not current water level.','https://www.nps.gov/glca/planyourvisit/lone-rock-beach.htm','Lone Rock Beach Primitive Camping Area')+'</div>';fork.after(page);
const moabPane=$('[data-loc="Corona Arch"] [data-tab="Events"]');if(moabPane){const row=document.createElement('div');row.className='card-row';row.innerHTML=card('Grand County vs Whitehorse','Friday September 25 · 7 p.m. · Moab','High-school homecoming football at Grand County High School, 608 South 400 East. A local Friday-night crowd without changing the route. The school calendar confirms the game; tickets and attendance estimates are not published. Check the calendar again before heading over.','https://gchs.grandschools.org/apps/events/','Grand County High School Moab');moabPane.prepend(row);}

setPhoto('Lone Rock Beach primitive camping','https://home.nps.gov/common/uploads/imr/park/glca/F124C619-E0A5-A118-7979024D9E30DBEA/F124C619-E0A5-A118-7979024D9E30DBEA.jpg?maxWidth=900','Lone Rock · NPS, June 2023','https://www.nps.gov/glca/planyourvisit/lone-rock-beach.htm');
const credits=document.createElement('details');credits.className='compact-credits';credits.innerHTML='<summary>Photo sources & credits</summary>';document.body.append(credits);
document.querySelectorAll('figcaption').forEach(cap=>{const original=cap.textContent.trim();const links=[...cap.querySelectorAll('a')];if(links.length){const p=document.createElement('p');p.textContent=original+' ';links.forEach(a=>p.append(a.cloneNode(true)));credits.append(p);}cap.title=original;let title=cap.closest('.discovery-card')?.querySelector('h4')?.textContent||original.split(' · ')[0];title=title.replace('Campground','camp').replace('Brewing Company','Brewing').replace('Frigid Air Pass / West Maroon circuit','Frigid Air approach').replace('Mount Sneffels summit via Yankee Boy Basin','Mount Sneffels').replace('West Maroon Pass toward Aspen','West Maroon trail').replace('Harrison Avenue, Leadville','Leadville · Harrison Ave').replace('Crested Butte area','Crested Butte');cap.textContent=title;});
})();
